version: '2'
services:
    saturno-app:
        image: saturno
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://saturno-postgresql:5432/Saturno
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    saturno-postgresql:
        extends:
            file: postgresql.yml
            service: saturno-postgresql
