version: '2'
services:
    saturno-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/Saturno/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Saturno
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
